create table album_images (extension varchar(5) not null, album_id uuid not null, type varchar(20) not null check ((type in ('COVER','BACK_COVER','BOOKLET','DISC','OTHER'))), identifier varchar(255) not null);
create table album_track_guests (display_order integer not null, person_id uuid not null, track_id uuid not null, credit_name varchar(255) not null);
create table album_tracks (disc_number integer not null, track_number integer not null, duration interval second(6) not null, isrc varchar(15), album_id uuid not null, composition_id uuid not null, id uuid not null, title varchar(200) not null, primary key (id));
create table albums (start_date date not null, artist_profile_id uuid not null, artist_profile_lineup_id uuid not null, id uuid not null, title varchar(200) not null, primary key (id));
create table artist_profiles (id uuid not null, artist_type varchar(20) not null check ((artist_type in ('SOLO','BAND','ORCHESTRA','CHOIR','DUO','ENSEMBLE'))), stage_name varchar(200) not null, biography TEXT, primary key (id));
create table composition_authors (author_id uuid not null, composition_id uuid not null);
create table compositions (release_date date, iswc varchar(15) not null, id uuid not null, title varchar(200) not null, lyrics TEXT, primary key (id));
create table lineup_members (is_founder boolean not null, is_main_artist boolean not null, lineup_id uuid not null, person_id uuid not null);
create table lineups (end_date date, start_date date not null, artist_profile_id uuid not null, id uuid not null, label varchar(200) not null, primary key (id));
create table persons (birth_date date not null, id uuid not null, name varchar(200) not null, primary key (id));
alter table if exists album_images add constraint fk_album_imagem foreign key (album_id) references albums;
alter table if exists album_track_guests add constraint fk_album_track_guest foreign key (track_id) references album_tracks;
alter table if exists album_tracks add constraint fk_album_track foreign key (album_id) references albums;
alter table if exists composition_authors add constraint fk_composition_author foreign key (composition_id) references compositions;
alter table if exists lineup_members add constraint fk_lineup_member foreign key (lineup_id) references lineups;
alter table if exists lineups add constraint fk_lineup foreign key (artist_profile_id) references artist_profiles;
alter table if exists albums add constraint fk_albums_artist_profile foreign key (artist_profile_id) references artist_profiles(id);
alter table if exists albums add constraint fk_albums_lineup foreign key (artist_profile_lineup_id) references lineups(id);
alter table if exists album_tracks add constraint fk_album_tracks_composition foreign key (composition_id) references compositions(id);
alter table if exists album_track_guests add constraint fk_album_track_guests_person foreign key (person_id) references persons(id);
alter table if exists lineup_members add constraint fk_lineup_members_lineup foreign key (lineup_id) references lineups(id);
alter table if exists lineup_members add constraint fk_lineup_members_person foreign key (person_id) references persons(id);
create index idx_album_imagem on album_images(album_id);
create index idx_album_track_guest on album_track_guests(track_id);
create index idx_album_track on album_tracks(album_id);
create index idx_composition_author on composition_authors(composition_id);
create index idx_lineup_member on lineup_members(lineup_id);
create index lineup on lineups(artist_profile_id);
create index idx_album_tracks_composition on album_tracks(composition_id);
create index idx_album_track_guests_person on album_track_guests(person_id);
create index idx_lineup_members_lineup on lineup_members(lineup_id);
create index idx_lineup_members_person on lineup_members(person_id);